harvester/charts

- .github/workflows/release.yaml
- README.md
- Add GitHub Action to release charts automatically.
- Update readme.
> Add release action

- charts/harvester-csi-driver/.helmignore
- charts/harvester-csi-driver/Chart.yaml
- charts/harvester-csi-driver/templates/NOTES.txt
- charts/harvester-csi-driver/templates/_helpers.tpl
- charts/harvester-csi-driver/templates/csidriver.yaml
- charts/harvester-csi-driver/templates/daemonset.yaml
- charts/harvester-csi-driver/templates/deployment.yaml
- charts/harvester-csi-driver/templates/rbac.yaml
- charts/harvester-csi-driver/templates/storageclass.yaml
- charts/harvester-csi-driver/values.yaml
issue: https://github.com/harvester/harvester/issues/1019
> Add harvester csi driver chart

- .github/workflows/ci.yaml
- charts/harvester-csi-driver/values.yaml
Fix the CI lint and update the Harvester csi image tag
> Fix CI and update csi tag

- charts/harvester-load-balancer/.helmignore
- charts/harvester-load-balancer/Chart.yaml
- charts/harvester-load-balancer/crds/loadbalancer.harvesterhci.io_loadbalancers.yaml
- charts/harvester-load-balancer/templates/_helpers.tpl
- charts/harvester-load-balancer/templates/deployment.yaml
- charts/harvester-load-balancer/templates/rbac.yaml
- charts/harvester-load-balancer/values.yaml
issue: https://github.com/harvester/harvester/issues/1019
> Add harvester load balancer chart

- charts/harvester-cloud-provider/.helmignore
- charts/harvester-cloud-provider/Chart.yaml
- charts/harvester-cloud-provider/ci/kind-values.yaml
- charts/harvester-cloud-provider/templates/_helpers.tpl
- charts/harvester-cloud-provider/templates/deployment.yaml
- charts/harvester-cloud-provider/templates/rbac.yaml
- charts/harvester-cloud-provider/values.yaml
issue: https://github.com/harvester/harvester/issues/1019
> Add harvester cloud provider chart

- charts/harvester-network-controller/templates/rbac.yaml
issue: https://github.com/harvester/harvester/issues/633
> Modify harvester network controller clusterrole to support vip

- charts/harvester-network-controller/templates/deployment.yaml
Enable hostnetwork for manager network controller
> Enable hostnetwork for manager network controller

- charts/harvester-node-disk-manager/crds/harvesterhci.io_blockdevices.yaml
Related: harvester/node-disk-manager#11
Signed-off-by: Weihang Lo <weihang.lo@suse.com>
> Update manifest for harvester-node-disk-manager

- charts/harvester-node-disk-manager/templates/daemonset.yaml
- charts/harvester-node-disk-manager/values.yaml
> Wait for https://github.com/harvester/node-disk-manager/pull/12
Expose cmd args to helm values
- `vendorFilter`
- `pathFilter`
- `labelFilter`
- `rescanInterval`
- `autoGPTGenerate`
> Add cmd args for node-disk-manager

- charts/harvester-node-disk-manager/Chart.yaml
- charts/harvester-node-disk-manager/templates/daemonset.yaml
- charts/harvester-node-disk-manager/values.yaml
> Blocked by the 0.2.0 tag existence on https://github.com/harvester/node-disk-manager
Related: https://github.com/harvester/charts/pull/34
> Release harvester-node-disk-manager 0.2.0

- charts/harvester-node-disk-manager/templates/daemonset.yaml
- charts/harvester-node-disk-manager/values.yaml
Related: 
- https://github.com/harvester/node-disk-manager/pull/17
- https://github.com/harvester/node-disk-manager/pull/16
> Add autoProvisionFilter value for node-disk-manager

- charts/harvester-node-disk-manager/Chart.yaml
- charts/harvester-node-disk-manager/templates/daemonset.yaml
- charts/harvester-node-disk-manager/values.yaml
> Note: Need to tag 0.3.0 on node-disk-manager first
Related: 
- https://github.com/harvester/node-disk-manager/pull/17
- https://github.com/harvester/node-disk-manager/pull/16
> Bump harvester-node-disk-manager to 0.3.0

- charts/harvester-cloud-provider/Chart.yaml
- charts/harvester-cloud-provider/templates/deployment.yaml
- charts/harvester-cloud-provider/templates/rbac.yaml
- charts/harvester-cloud-provider/values.yaml
- charts/harvester-csi-driver/Chart.yaml
- charts/harvester-csi-driver/templates/daemonset.yaml
- charts/harvester-csi-driver/values.yaml
Related pr: https://github.com/rancher/charts/pull/1595
> Sync to rancher charts

- charts/harvester-cloud-provider/Chart.yaml
- charts/harvester-cloud-provider/templates/deployment.yaml
- charts/harvester-cloud-provider/templates/rbac.yaml
- charts/harvester-cloud-provider/values.yaml
- charts/harvester-csi-driver/Chart.yaml
- charts/harvester-csi-driver/templates/daemonset.yaml
- charts/harvester-csi-driver/values.yaml
Sync https://github.com/harvester/charts/pull/45
> Sync modification from release

- charts/harvester-network-controller/templates/deployment.yaml
- charts/harvester-network-controller/values.yaml
Add helper image flag for the harvester-network-controller-manager
Related issue: https://github.com/harvester/harvester/issues/1476
> Add helper image flag

- charts/harvester-network-controller/Chart.yaml
- charts/harvester-network-controller/templates/deployment.yaml
- charts/harvester-network-controller/values.yaml
Release Harvester network controller v0.25
> Release Harvester network controller v0.25

- charts/harvester-node-disk-manager/Chart.yaml
Fixes
- https://github.com/harvester/node-disk-manager/pull/20
- https://github.com/harvester/node-disk-manager/pull/19
> Release harvester-node-disk-manager 0.3.2

- charts/harvester-cloud-provider/Chart.yaml
- charts/harvester-cloud-provider/questions.yml
- charts/harvester-cloud-provider/templates/_helpers.tpl
- charts/harvester-cloud-provider/values.yaml
- charts/harvester-csi-driver/Chart.yaml
- charts/harvester-csi-driver/questions.yml
- charts/harvester-csi-driver/templates/_helpers.tpl
- charts/harvester-csi-driver/templates/daemonset.yaml
- charts/harvester-csi-driver/templates/deployment.yaml
- charts/harvester-csi-driver/values.yaml
Related pr: https://github.com/rancher/charts/pull/1595
> Fix review issues for adding into rancher charts

- charts/harvester-network-controller/templates/deployment.yaml
Related issue: https://github.com/harvester/harvester/issues/1611
> Network helper image env should not include quotation marks

- charts/harvester-cloud-provider/Chart.yaml
- charts/harvester-cloud-provider/questions.yml
- charts/harvester-cloud-provider/values.yaml
- charts/harvester-csi-driver/Chart.yaml
- charts/harvester-csi-driver/questions.yml
- charts/harvester-csi-driver/templates/storageclass.yaml
- charts/harvester-csi-driver/values.yaml
Related issue: 
https://github.com/rancher/rancher/issues/35000
https://github.com/harvester/harvester/issues/1629
> Release harvester cloud provider chart 0.1.6 and csi driver chart 0.1.7

- charts/harvester-cloud-provider/Chart.yaml
- charts/harvester-csi-driver/Chart.yaml
Related PR: https://github.com/rancher/charts/pull/1649#pullrequestreview-830751448
> Fix the comment issue by the rancher teams

- charts/harvester-cloud-provider/Chart.yaml
- charts/harvester-cloud-provider/questions.yml
- charts/harvester-cloud-provider/templates/_helpers.tpl
- charts/harvester-cloud-provider/values.yaml
- charts/harvester-csi-driver/Chart.yaml
- charts/harvester-csi-driver/questions.yml
- charts/harvester-csi-driver/templates/_helpers.tpl
- charts/harvester-csi-driver/templates/daemonset.yaml
- charts/harvester-csi-driver/templates/deployment.yaml
- charts/harvester-csi-driver/templates/storageclass.yaml
- charts/harvester-csi-driver/values.yaml
Cherry-pick from the release branch. 
commit: 
https://github.com/harvester/charts/commit/0665a6a2f76762bd963b0e8f4566a41e0fd67c41
https://github.com/harvester/charts/commit/f3d1b8bfe96b5a6820df1fe45d480bbd05174f70
> Sync From release

- charts/harvester-node-disk-manager/crds/harvesterhci.io_blockdevices.yaml
Related: harvester/harvester#1334, harvester/node-disk-manager#22
> Add provisionPhase for blockdevice

- charts/harvester-node-disk-manager/Chart.yaml
- charts/harvester-node-disk-manager/crds/harvesterhci.io_blockdevices.yaml
Related: harvester/harvester#1334, harvester/node-disk-manager#22, https://github.com/harvester/charts/pull/61
> Release harvester-node-disk-manager 0.4.0

- charts/harvester-cloud-provider/Chart.yaml
- charts/harvester-csi-driver/Chart.yaml
Sync from release branch to remove the experimental tag for harvester cloud provider and harvester csi driver.
> Remove experimental

- charts/harvester-network-controller/templates/_helpers.tpl
- charts/harvester-network-controller/templates/deployment.yaml
- charts/harvester-network-controller/values.yaml
related issue https://github.com/harvester/harvester/issues/1722
> Add required anti-affinity for harvester network manager

- charts/harvester-csi-driver/templates/daemonset.yaml
- charts/harvester-csi-driver/values.yaml
Related issue: https://github.com/harvester/harvester/issues/1895
Dependency PR: https://github.com/harvester/harvester-csi-driver/pull/6
> Add default kubeconfig path for csi driver

- charts/harvester-cloud-provider/templates/deployment.yaml
- charts/harvester-cloud-provider/values.yaml
Related issue: https://github.com/harvester/harvester/issues/1999
> Enable hostnetwork for cloud provider

- charts/harvester-load-balancer/Chart.yaml
- charts/harvester-network-controller/Chart.yaml
- charts/harvester-node-disk-manager/Chart.yaml
Bump harvester LB, network, and NDM version
> Bump harvester LB, network and NDM version

- charts/harvester-cloud-provider/Chart.yaml
Related issue:
https://github.com/harvester/harvester/issues/2041
https://github.com/harvester/harvester/issues/2122
> Update cloud provider image to v0.1.3

- charts/harvester-cloud-provider/Chart.yaml
- charts/harvester-cloud-provider/values.yaml
Related issue:
https://github.com/harvester/harvester/issues/2041
https://github.com/harvester/harvester/issues/2122
> Release harvester-cloud-provider 0.1.11

- charts/harvester-csi-driver/Chart.yaml
- charts/harvester-csi-driver/templates/daemonset.yaml
- charts/harvester-csi-driver/values.yaml
Bump CSI driver and use the default `appVersion` tag.
Related Issue:
https://github.com/harvester/harvester/issues/2151
> Bump CSI driver and use the default appVersion tag

- charts/harvester-node-disk-manager/templates/crds/harvesterhci.io_blockdevices.yaml
Add `blockdevice.status.deviceStatus.devPath`
Blocked on https://github.com/harvester/node-disk-manager/pull/35
> Update CRDs of node-disk-manager

- charts/harvester-cloud-provider/Chart.yaml
- charts/harvester-cloud-provider/questions.yml
- charts/harvester-cloud-provider/templates/deployment.yaml
- charts/harvester-cloud-provider/values.yaml
Related issue: https://github.com/harvester/harvester/issues/2031
> Release harvester cloud provider 0.1.12

- charts/harvester-node-disk-manager/Chart.yaml
- charts/harvester-node-disk-manager/templates/crds/harvesterhci.io_blockdevices.yaml
cherry picked from #79 
related release: https://github.com/harvester/node-disk-manager/releases/tag/v0.4.2
> Release harvester-node-disk-manager 0.4.3

- charts/harvester-csi-driver/Chart.yaml
Related issue: https://github.com/rancher/rancher/issues/37738
Fix review comments
> Modify harvester-csi-driver chart annotations

- charts/harvester-node-disk-manager/templates/daemonset.yaml
- charts/harvester-node-disk-manager/values.yaml
That is for the latest NDM parameter
> chart: add `max concurrent ops` to daemonset

- charts/harvester-cloud-provider/Chart.yaml
- charts/harvester-cloud-provider/values.yaml
Release issue: harvester/harvester#1418
> Release harvester cloud provider 0.1.13

- charts/harvester-node-disk-manager/Chart.yaml
- charts/harvester-node-disk-manager/templates/daemonset.yaml
- charts/harvester-node-disk-manager/values.yaml
- Add NDM v0.4.4 release https://github.com/harvester/node-disk-manager/releases/tag/v0.4.4
- backport master PR https://github.com/harvester/charts/pull/88
> Add NDM v0.4.4 release

- charts/harvester-vm-import-controller/.helmignore
- charts/harvester-vm-import-controller/Chart.yaml
- charts/harvester-vm-import-controller/templates/_helpers.tpl
- charts/harvester-vm-import-controller/templates/deployment.yaml
- charts/harvester-vm-import-controller/templates/pvc.yaml
- charts/harvester-vm-import-controller/templates/rbac.yaml
- charts/harvester-vm-import-controller/templates/service.yaml
- charts/harvester-vm-import-controller/templates/serviceaccount.yaml
- charts/harvester-vm-import-controller/values.yaml
The PR introduces the vm-import-controller chart, to allow packaging of same with harvester chart.
> Addition of vm-import-controller chart

- charts/harvester-pcidevices-controller/.helmignore
- charts/harvester-pcidevices-controller/Chart.yaml
- charts/harvester-pcidevices-controller/templates/_helpers.tpl
- charts/harvester-pcidevices-controller/templates/daemonset.yaml
- charts/harvester-pcidevices-controller/templates/serviceaccount.yaml
- charts/harvester-pcidevices-controller/values.yaml
The PR introduces the helm chart for the pcidevices controller: https://github.com/harvester/pcidevices
> initial commit for pcidevices controller

- charts/harvester-vm-import-controller/.helmignore
- charts/harvester-vm-import-controller/Chart.yaml
- charts/harvester-vm-import-controller/templates/_helpers.tpl
- charts/harvester-vm-import-controller/templates/deployment.yaml
- charts/harvester-vm-import-controller/templates/pvc.yaml
- charts/harvester-vm-import-controller/templates/rbac.yaml
- charts/harvester-vm-import-controller/templates/service.yaml
- charts/harvester-vm-import-controller/templates/serviceaccount.yaml
- charts/harvester-vm-import-controller/values.yaml
v0.1.0 of vm-import-controller
> release vm-import-controller v0.1.0

- charts/harvester-pcidevices-controller/Chart.yaml
- charts/harvester-pcidevices-controller/templates/daemonset.yaml
- charts/harvester-pcidevices-controller/templates/serviceaccount.yaml
changes to pcidevices chart to support additional webhook.
> update to pcidevices chart

- charts/harvester-pcidevices-controller/.helmignore
- charts/harvester-pcidevices-controller/Chart.yaml
- charts/harvester-pcidevices-controller/templates/_helpers.tpl
- charts/harvester-pcidevices-controller/templates/daemonset.yaml
- charts/harvester-pcidevices-controller/templates/serviceaccount.yaml
- charts/harvester-pcidevices-controller/values.yaml
PR introduces initial release using `v0.2.1-rc1` for the pcidevices controller.
> Initial releases for pcidevices chart

- charts/harvester-node-manager/.helmignore
- charts/harvester-node-manager/Chart.yaml
- charts/harvester-node-manager/templates/NOTES.txt
- charts/harvester-node-manager/templates/_helpers.tpl
- charts/harvester-node-manager/templates/crds/node.harvesterhci.io_ksmtuneds.yaml
- charts/harvester-node-manager/templates/daemonset.yaml
- charts/harvester-node-manager/templates/rbac.yaml
- charts/harvester-node-manager/values.yaml
- Initialize Node Manager code.
- Add Ksmtuned Controller manage KSM of node.
**Related issue**
https://github.com/harvester/harvester/issues/2302
**Dependency PR**
https://github.com/harvester/node-manager/pull/1
> add node-manager chart

- charts/harvester-node-manager/.helmignore
- charts/harvester-node-manager/Chart.yaml
- charts/harvester-node-manager/templates/NOTES.txt
- charts/harvester-node-manager/templates/_helpers.tpl
- charts/harvester-node-manager/templates/crds/node.harvesterhci.io_ksmtuneds.yaml
- charts/harvester-node-manager/templates/daemonset.yaml
- charts/harvester-node-manager/templates/rbac.yaml
- charts/harvester-node-manager/values.yaml
> release node-manager v0.1.0

- charts/harvester-pcidevices-controller/Chart.yaml
- charts/harvester-pcidevices-controller/templates/daemonset.yaml
- charts/harvester-pcidevices-controller/templates/service.yaml
cherry pick of latest changes for pcidevices
> new release for pcidevices

- charts/harvester-pcidevices-controller/templates/daemonset.yaml
- charts/harvester-pcidevices-controller/templates/service.yaml
- charts/harvester-pcidevices-controller/templates/serviceaccount.yaml
fixes https://github.com/harvester/harvester/issues/2802
* https://github.com/harvester/pcidevices/commit/b1c003e4f09af18e8773fb6157a2d5e53197cae5
* https://github.com/harvester/pcidevices/commit/a9bca44af8e99228e29f693cc9cc1aaafeab87ca
* https://github.com/harvester/pcidevices/commit/f95066f4c9738fb68514a56084792557e74c9bf9
> Update PCI devices controller daemonset

- charts/harvester-pcidevices-controller/Chart.yaml
- charts/harvester-pcidevices-controller/templates/daemonset.yaml
- charts/harvester-pcidevices-controller/templates/service.yaml
- charts/harvester-pcidevices-controller/templates/serviceaccount.yaml
- charts/harvester-pcidevices-controller/values.yaml
Backport of:
- https://github.com/harvester/charts/pull/110
- https://github.com/harvester/charts/pull/111
and bump chart version.
> harvester-pcidevices-controller: release 0.2.0-rc3

- charts/harvester-vm-import-controller/Chart.yaml
- charts/harvester-vm-import-controller/templates/deployment.yaml
- charts/harvester-vm-import-controller/templates/pvc.yaml
- charts/harvester-vm-import-controller/values.yaml
Release vm-import-cotroller `v0.1.1-rc1`
> Release vm import v0.1.1-rc1

- charts/harvester-vm-import-controller/templates/service.yaml
Minor changes to VM import controller to use a predefined service name.
> changes to vm-import-controller

- charts/harvester-node-manager/Chart.yaml
- charts/harvester-node-manager/templates/crds/node.harvesterhci.io_ksmtuneds.yaml
- charts/harvester-node-manager/values.yaml
add Ksmtuned merge_across_nodes
**Related issue**
https://github.com/harvester/harvester/issues/2827
> Bump node-manager to v0.1.1

- charts/harvester-node-manager/Chart.yaml
- charts/harvester-node-manager/templates/crds/node.harvesterhci.io_ksmtuneds.yaml
- charts/harvester-node-manager/values.yaml
v0.1.1 of node-manager
**Related PR:**
https://github.com/harvester/charts/pull/118
> add KSM merge-across-nodes

- charts/harvester-node-manager/Chart.yaml
**Related PR:** 
https://github.com/harvester/charts/pull/119
> Bump chart version to 0.1.1

- charts/harvester-network-controller/templates/crds/network.harvesterhci.io_clusternetworks.yaml
- charts/harvester-network-controller/templates/crds/network.harvesterhci.io_nodenetworks.yaml
- charts/harvester-network-controller/templates/crds/network.harvesterhci.io_vlanconfigs.yaml
- charts/harvester-network-controller/templates/rbac.yaml
Related issue:
https://github.com/harvester/harvester/issues/2828
https://github.com/harvester/harvester/issues/2841
https://github.com/harvester/harvester/issues/2734
> Add clusternetwork status and reserve nodenetwork CRD

- charts/harvester-pcidevices-controller/templates/serviceaccount.yaml
Minor tweaks to pcidevices to allow access to kubevirts.io resources.
> RBAC changes for pcidevices

- charts/harvester-pcidevices-controller/Chart.yaml
- charts/harvester-pcidevices-controller/templates/serviceaccount.yaml
PR to retrofit changes for pr: https://github.com/harvester/charts/pull/123
> Release pcidevices rc2

- charts/harvester-pcidevices-controller/Chart.yaml
- charts/harvester-pcidevices-controller/templates/serviceaccount.yaml
New release for pcidevices chart
> Pcidevice 0.2.1 rc3

- charts/harvester-network-controller/templates/crds/network.harvesterhci.io_linkmonitors.yaml
- charts/harvester-network-controller/templates/crds/network.harvesterhci.io_nodenetworks.yaml
- charts/harvester-network-controller/templates/rbac.yaml
Related issue: https://github.com/harvester/harvester/issues/2794
> Add linkmonitor

- charts/harvester-network-controller/Chart.yaml
- charts/harvester-network-controller/values.yaml
Signed-off-by: Canwu Yao <yaocanwu@gmail.com>
> Release harvester-network-controller 0.3.0

- charts/harvester-pcidevices-controller/Chart.yaml
**Description:**
Add pci-devices v0.2.1 release for the Harvester v1.1.0 formal release.
> Add pci-devices v0.2.1 release

- charts/harvester-node-manager/Chart.yaml
- charts/harvester-pcidevices-controller/Chart.yaml
node-manager v0.1.2
pcidevices v0.2.2
> Bump node-manager and pcidevices

- charts/harvester-network-controller/Chart.yaml
- charts/harvester-network-controller/values.yaml
- charts/harvester-node-disk-manager/Chart.yaml
- charts/harvester-node-manager/Chart.yaml
- charts/harvester-pcidevices-controller/Chart.yaml
- charts/harvester-vm-import-controller/Chart.yaml
**Description:**
Bump chart and image versions of the OS package update.
**Related Issue:**
https://github.com/harvester/harvester/issues/3159
> chart: bump chart and image versions of os package update

- charts/harvester-csi-driver/Chart.yaml
- charts/harvester-csi-driver/values.yaml
bump harvester-csi-driver to v0.1.4
> charts: bump harvester-csi-driver to v0.1.4

- charts/harvester-csi-driver/Chart.yaml
Missing version bump on the previous commit.
> build: fix missing version bump

- charts/harvester-pcidevices-controller/Chart.yaml
- charts/harvester-pcidevices-controller/templates/daemonset.yaml
release for new version of pcidevices controller.
> Pcidevices 0.2.4 rc1

- charts/harvester-network-controller/templates/rbac.yaml
Related issue: https://github.com/harvester/harvester/issues/3372
> Modify network webhook RBAC

- charts/harvester-load-balancer/Chart.yaml
Related issue: https://github.com/harvester/harvester/issues/3149
> Release harvester load balancer 0.1.4

- charts/harvester-network-controller/Chart.yaml
- charts/harvester-network-controller/templates/rbac.yaml
- charts/harvester-network-controller/values.yaml
Related issue: https://github.com/harvester/harvester/issues/3372
> Release harvester network controller 0.3.2-rc1

- charts/harvester-pcidevices-controller/templates/serviceaccount.yaml
Tested this on my cluster, this works
> Add RBAC permissions for node cleanup

- charts/harvester-pcidevices-controller/Chart.yaml
- charts/harvester-pcidevices-controller/templates/serviceaccount.yaml
PR introduces changes for new release of pcidevices-controller chart
> new release for pcidevices controller chart

- charts/harvester-vm-import-controller/Chart.yaml
PR introduces a change of version for vm-import-controller to support new vm-import-controller image.
> bump version of vm-import-controller to v0.1.3

- charts/harvester-pcidevices-controller/Chart.yaml
- charts/harvester-pcidevices-controller/templates/daemonset.yaml
PR to introduce new chart version for pcidevices controller.
New chart includes following changes:
https://github.com/harvester/pcidevices/pull/52
https://github.com/harvester/pcidevices/pull/53
> Pcidevices controller v0.2.4 rc3

- charts/harvester-network-controller/templates/crds/network.harvesterhci.io_vlanconfigs.yaml
Related issue: https://github.com/harvester/harvester/issues/3744
> Add validation and default for vlanconfig parameters

- charts/harvester-network-controller/Chart.yaml
- charts/harvester-network-controller/templates/crds/network.harvesterhci.io_vlanconfigs.yaml
- charts/harvester-network-controller/values.yaml
Related issue: https://github.com/harvester/harvester/issues/3744
Backport of https://github.com/harvester/charts/pull/155
> Release harvester network controller 0.3.2-rc5

- charts/harvester-vm-import-controller/Chart.yaml
PR to update vm-import-controller to new image to address CVE's.
Related issue: https://github.com/harvester/security/issues/29
> bump up vm-import-controller to v0.1.4

- charts/harvester-node-manager/Chart.yaml
PR to update node-manager to new image to address CVEs.
Related issue: https://github.com/harvester/security/issues/29
> Bump up node manager to v0.1.4

- charts/harvester-network-controller/Chart.yaml
- charts/harvester-network-controller/values.yaml
**Description:**
Add network-controller v0.3.2  release
> Add network-controller v0.3.2 release

- charts/harvester-pcidevices-controller/Chart.yaml
PR to bump up pcidevices chart to v0.2.4
> pcidevices version 0.2.4

- charts/harvester-load-balancer/Chart.yaml
- charts/harvester-load-balancer/templates/_helpers.tpl
- charts/harvester-load-balancer/templates/crds/loadbalancer.harvesterhci.io_ippools.yaml
- charts/harvester-load-balancer/templates/crds/loadbalancer.harvesterhci.io_loadbalancers.yaml
- charts/harvester-load-balancer/templates/deployment.yaml
- charts/harvester-load-balancer/templates/rbac.yaml
- charts/harvester-load-balancer/templates/service.yaml
- charts/harvester-load-balancer/values.yaml
- Upgrade harvester load balancer from v1alpha1 to v1beta1
- Add IPPool
- Add harvester load balancer webhook
Related issue: https://github.com/harvester/harvester/issues/1580
> Upgrade load balancer to v1beta1

- charts/harvester-load-balancer/Chart.yaml
- charts/harvester-load-balancer/templates/_helpers.tpl
- charts/harvester-load-balancer/templates/crds/loadbalancer.harvesterhci.io_ippools.yaml
- charts/harvester-load-balancer/templates/crds/loadbalancer.harvesterhci.io_loadbalancers.yaml
- charts/harvester-load-balancer/templates/deployment.yaml
- charts/harvester-load-balancer/templates/rbac.yaml
- charts/harvester-load-balancer/templates/service.yaml
- charts/harvester-load-balancer/values.yaml
Related issue: https://github.com/harvester/harvester/issues/1762
> Release harvester load balancer 0.2.0-rc1

- charts/harvester-load-balancer/templates/deployment.yaml
Related issue: https://github.com/harvester/harvester/issues/4000
> Modify load balancer webhook resources

- charts/harvester-load-balancer/Chart.yaml
- charts/harvester-load-balancer/templates/deployment.yaml
- charts/harvester-load-balancer/values.yaml
Related issue: https://github.com/harvester/harvester/issues/4000
> Release harvester load balancer 0.2.0-rc2

- charts/harvester-cloud-provider/Chart.yaml
- charts/harvester-cloud-provider/values.yaml
Release harvester cloud provider 0.2.1
Update the image tag to v0.2.0
Related issue: https://github.com/harvester/harvester/issues/1762
> Release harvester cloud provider 0.2.1

- charts/harvester-node-manager/templates/crds/node.harvesterhci.io_nodeconfigs.yaml
- charts/harvester-node-manager/templates/daemonset.yaml
- charts/harvester-node-manager/templates/rbac.yaml
- with the latest node-manager changes, we also need to update here
That changes should be merged after https://github.com/harvester/node-manager/pull/10
> charts: update volume related configuration and rbac

- charts/harvester-cloud-provider/Chart.yaml
- charts/harvester-cloud-provider/values.yaml
https://github.com/rancher/rke2/issues/4184
> Release harvester cloud provider 0.2.2

- charts/harvester-seeder/.helmignore
- charts/harvester-seeder/Chart.yaml
- charts/harvester-seeder/templates/_helpers.tpl
- charts/harvester-seeder/templates/deployment.yaml
- charts/harvester-seeder/templates/rbac.yaml
- charts/harvester-seeder/templates/role-binding.yaml
- charts/harvester-seeder/templates/service.yaml
- charts/harvester-seeder/templates/serviceaccount.yaml
- charts/harvester-seeder/values.yaml
Introduction of base chart for harvester-seeder
Related to: https://github.com/harvester/harvester/issues/2318
> initial commit for harvester-seeder helm chart

- charts/harvester-pcidevices-controller/Chart.yaml
PR introduces v0.2.5-rc2 for pcidevices.
> version v0.2.5-rc2 for pcidevices

- charts/harvester-node-disk-manager/Chart.yaml
- charts/harvester-node-disk-manager/templates/crds/harvesterhci.io_blockdevices.yaml
- charts/harvester-node-disk-manager/templates/daemonset.yaml
- charts/harvester-node-disk-manager/values.yaml
- follow the latest NDM release
> charts: bump harvester-node-disk-manager to v0.5.0

- .github/workflows/ci.yaml
- charts/harvester-seeder/.helmignore
- charts/harvester-seeder/Chart.yaml
- charts/harvester-seeder/templates/_helpers.tpl
- charts/harvester-seeder/templates/deployment.yaml
- charts/harvester-seeder/templates/rbac.yaml
- charts/harvester-seeder/templates/role-binding.yaml
- charts/harvester-seeder/templates/service.yaml
- charts/harvester-seeder/templates/serviceaccount.yaml
- charts/harvester-seeder/values.yaml
PR contains release for seeder chart v0.1.0-rc2
since seeder needs `harvester-system` namespace to exist the CI has an additional step to create `harvester-system` namespace.
> release for v0.1.0-rc2

- charts/harvester-vm-import-controller/Chart.yaml
PR bumps up vm-import-controller to v0.1.5
> v0.1.5 for vm-import-controller

- charts/harvester-pcidevices-controller/Chart.yaml
PR updates pcidevices controller chart to v0.2.5
> update pcidevices to v0.2.5

- charts/harvester-seeder/Chart.yaml
- charts/harvester-seeder/templates/deployment.yaml
- charts/harvester-seeder/templates/rbac.yaml
- charts/harvester-seeder/templates/service.yaml
- charts/harvester-seeder/values.yaml
PR updates seeder addon to v0.1.0-rc3
> Seeder v0.1.0-rc3

- charts/harvester-seeder/Chart.yaml
PR updates seeder chart to v0.1.0
> updated seeder chart to v0.1.0

- charts/harvester-vm-import-controller/Chart.yaml
PR introduces a new version vm-import-controller
> introduce vm-import-controller v0.1.6 chart

- charts/harvester-pcidevices-controller/Chart.yaml
update pcidevices controller to v0.2.6
> bump pcidevices controller to v0.2.6

- charts/harvester-node-manager/values.yaml
- Even in etcd node, node-manager should run for time sync
> chart: update tolerations of node-manager

- charts/harvester-vm-import-controller/Chart.yaml
PR updates vm-import-controller to v0.1.7
> bump vm-import-controller to v0.1.7

- charts/harvester-seeder/Chart.yaml
PR to update seeder chart to new v0.1.1 image.
> update seeder chart to v0.1.1

- charts/harvester-pcidevices-controller/Chart.yaml
update pcidevices chart to v0.3.0
> update pcidevices chart to v0.3.0

- charts/nvidia-driver-runtime/.helmignore
- charts/nvidia-driver-runtime/Chart.yaml
- charts/nvidia-driver-runtime/templates/_helpers.tpl
- charts/nvidia-driver-runtime/templates/daemonset.yaml
- charts/nvidia-driver-runtime/templates/serviceaccount.yaml
- charts/nvidia-driver-runtime/values.yaml
Base chart for deploying nvidia-drivers using a container image. 
Related to: https://github.com/harvester/harvester/issues/2764
> chart for nvidia-driver-runtime

- charts/nvidia-driver-runtime/.helmignore
- charts/nvidia-driver-runtime/Chart.yaml
- charts/nvidia-driver-runtime/templates/_helpers.tpl
- charts/nvidia-driver-runtime/templates/daemonset.yaml
- charts/nvidia-driver-runtime/templates/serviceaccount.yaml
- charts/nvidia-driver-runtime/values.yaml
initial release for nvidia-driver-toolkit chart.
This is needed to prepare addon for same.
> Release nvidia driver toolkit

- charts/harvester-pcidevices-controller/templates/daemonset.yaml
- charts/harvester-pcidevices-controller/templates/serviceaccount.yaml
- charts/harvester-pcidevices-controller/values.yaml
PR introduces changes needed in the pcidevices controller chart for manage gpu/vgpu devices.
> Pcidevices vgpu support

- charts/harvester-pcidevices-controller/Chart.yaml
- charts/harvester-pcidevices-controller/templates/daemonset.yaml
- charts/harvester-pcidevices-controller/templates/serviceaccount.yaml
- charts/harvester-pcidevices-controller/values.yaml
PR cherry picks the chart changes for pcidevices controller and bumps up chart version
> Pcidevices v0.3.1

- charts/harvester-node-manager/templates/_helpers.tpl
- charts/harvester-node-manager/templates/crds/node.harvesterhci.io_cloudinits.yaml
- charts/harvester-node-manager/templates/deployment.yaml
- charts/harvester-node-manager/templates/rbac.yaml
- charts/harvester-node-manager/templates/service.yaml
- charts/harvester-node-manager/values.yaml
> harvester-node-manager: add webhook

- charts/harvester-node-disk-manager/Chart.yaml
- charts/harvester-node-disk-manager/templates/crds/harvesterhci.io_blockdevices.yaml
We still need another commit to specify the NDM version (should be v0.6.1)
Keep it draft
> Bump NDM and update CRD

- charts/harvester-node-disk-manager/templates/crds/harvesterhci.io_blockdevices.yaml
update the CRD for NDM master-head
> templates: update blockdevice CRD of node-disk-manager

- charts/harvester-vm-dhcp-controller/.helmignore
- charts/harvester-vm-dhcp-controller/Chart.yaml
- charts/harvester-vm-dhcp-controller/crds/network.harvesterhci.io_ippools.yaml
- charts/harvester-vm-dhcp-controller/crds/network.harvesterhci.io_virtualmachinenetworkconfigs.yaml
- charts/harvester-vm-dhcp-controller/templates/NOTES.txt
- charts/harvester-vm-dhcp-controller/templates/_helpers.tpl
- charts/harvester-vm-dhcp-controller/templates/deployment.yaml
- charts/harvester-vm-dhcp-controller/templates/rbac.yaml
- charts/harvester-vm-dhcp-controller/templates/service.yaml
- charts/harvester-vm-dhcp-controller/templates/serviceaccount.yaml
- charts/harvester-vm-dhcp-controller/values.yaml
Add harvester-vm-dhcp-controller chart
Related issue: harvester/harvester#4428
> feat: introduce harvester-vm-dhcp-controller chart

- charts/harvester-pcidevices-controller/Chart.yaml
PR updates pcidevices controller to v0.3.2
The latest image for pcidevices controller includes the fix: https://github.com/harvester/pcidevices/pull/65
> bump pcidevices controller to v0.3.2

- charts/harvester-vm-dhcp-controller/Chart.yaml
- charts/harvester-vm-dhcp-controller/crds/network.harvesterhci.io_ippools.yaml
- charts/harvester-vm-dhcp-controller/crds/network.harvesterhci.io_virtualmachinenetworkconfigs.yaml
- charts/harvester-vm-dhcp-controller/values.yaml
> Bump vm dhcp controller 0.2.0

- charts/harvester-node-manager/Chart.yaml
- charts/harvester-node-manager/templates/deployment.yaml
Related issues: 
* https://github.com/harvester/harvester/issues/5210 
* https://github.com/harvester/harvester/issues/5212
> node-manager: Bump to v0.2.3

- charts/harvester-cloud-provider/Chart.yaml
- charts/harvester-cloud-provider/values.yaml
https://github.com/harvester/harvester/issues/4947
> Bump harvester-cloud-provider to v0.2.4

- charts/harvester-vm-dhcp-controller/templates/deployment.yaml
- charts/harvester-vm-dhcp-controller/values.yaml
Related issue: harvester/harvester#5153
> fix: add service cidr value for vm-dhcp-webhook

- charts/harvester-pcidevices-controller/Chart.yaml
PR updates pcidevices controller chart to v0.2.7
> pcidevices v0.2.7 update

- charts/harvester-vm-import-controller/Chart.yaml
- charts/harvester-vm-import-controller/templates/deployment.yaml
PR updates vm-import-controller to v0.1.8
It also includes the cherry-picked commit from master branch for deployment strategy.
> vm-import-controller v0.1.8

- charts/harvester-network-controller/Chart.yaml
- charts/harvester-network-controller/values.yaml
link: https://github.com/harvester/harvester/issues/5947
> bump: harvester-network-controller to v0.4.0

- charts/harvester-seeder/Chart.yaml
- charts/harvester-vm-import-controller/Chart.yaml
PR updates seeder and vm-import-controller to new versioning schema.
Related to: https://github.com/harvester/harvester/issues/5947
> chore: update seeder and vm-import-controller chart to new versioning schema

- charts/harvester-cloud-provider/Chart.yaml
- charts/harvester-cloud-provider/templates/deployment.yaml
Related issue: harvester/harvester#5348
> Bump cloud provider 0.2.5

- charts/harvester-pcidevices-controller/templates/daemonset.yaml
https://github.com/harvester/harvester/issues/5762
> feat(pcidevices-controller): mount /dev/bus

- charts/harvester-csi-driver-lvm/Chart.yaml
- charts/harvester-csi-driver-lvm/templates/_helpers.tpl
- charts/harvester-csi-driver-lvm/templates/common.yaml
- charts/harvester-csi-driver-lvm/templates/controller.yaml
- charts/harvester-csi-driver-lvm/templates/csi.yaml
- charts/harvester-csi-driver-lvm/templates/rbac.yaml
- charts/harvester-csi-driver-lvm/values.yaml
Initial commit for csi-driver-lvm
> charts: initial commit for csi-driver-lvm

- charts/harvester-csi-driver-lvm/Chart.yaml
- charts/harvester-csi-driver-lvm/templates/_helpers.tpl
- charts/harvester-csi-driver-lvm/templates/common.yaml
- charts/harvester-csi-driver-lvm/templates/controller.yaml
- charts/harvester-csi-driver-lvm/templates/csi.yaml
- charts/harvester-csi-driver-lvm/templates/rbac.yaml
- charts/harvester-csi-driver-lvm/values.yaml
Create first release of harvester-csi-driver-lvm
> charts: release v0.1.1 harvester-csi-driver-lvm

- charts/harvester-pcidevices-controller/Chart.yaml
- charts/harvester-pcidevices-controller/templates/daemonset.yaml
https://github.com/harvester/harvester/issues/5762
> bump(pcidevices-controller): v0.3.2 to v0.4.0

- charts/harvester-node-disk-manager/Chart.yaml
bump new version for harvester v1.4
> charts: bump NDM v0.7.0 for harvester v1.4

- charts/harvester-vm-import-controller/Chart.yaml
release vm-import-controller chart v0.3.2
> vm-import-controller chart release v0.3.2

- charts/harvester-pcidevices-controller/Chart.yaml
pcidevices controller chart v0.3.3
> pcidevices chart release v0.3.3

- charts/harvester-seeder/Chart.yaml
PR bumps seeder image to v0.3.2
> update seeder to v0.3.2

- charts/harvester-network-controller/Chart.yaml
- charts/harvester-network-controller/values.yaml
link: https://github.com/harvester/harvester/issues/6158
> bump: harvester-network-controller to v0.5.0

- README.md
> README: update the release HowTo and branch usage

- charts/harvester-node-manager/Chart.yaml
link: https://github.com/harvester/harvester/issues/6158
> Bump node-manager chart and appVersion to v0.3.0

- charts/harvester-node-manager/values.yaml
see comment https://github.com/harvester/charts/pull/264#issuecomment-2301528878
> Update node manager webhook image version

- charts/harvester-node-disk-manager/Chart.yaml
- charts/harvester-node-disk-manager/templates/crds/harvesterhci.io_blockdevices.yaml
- update the blockdevice CRD with new fields
> chars: update NDM chart v0.7.1

- charts/harvester-node-disk-manager/templates/crds/harvesterhci.io_blockdevices.yaml
> chart: update blockdevice CRD

- charts/harvester-node-manager/templates/crds/node.harvesterhci.io_nodeconfigs.yaml
- charts/harvester-node-manager/templates/daemonset.yaml
This picks up the changes from https://github.com/harvester/node-manager/pull/55
Related issue: https://github.com/harvester/harvester/issues/5274
> feat(harvester-node-manager): Add support for Longhorn V2 Data Engine

- charts/harvester-node-manager/Chart.yaml
- charts/harvester-node-manager/templates/crds/node.harvesterhci.io_nodeconfigs.yaml
- charts/harvester-node-manager/templates/daemonset.yaml
- charts/harvester-node-manager/values.yaml
This is the release part of https://github.com/harvester/charts/pull/269
> Bump node-manager to v0.3.1

- charts/harvester-resourcequotas-roles/Chart.yaml
https://github.com/harvester/harvester/issues/4478
> fix(harvester-resourcequotas-roles): change chart version to 0.0.0-dev

- charts/harvester-networkfs-manager/.helmignore
- charts/harvester-networkfs-manager/Chart.yaml
- charts/harvester-networkfs-manager/templates/NOTES.txt
- charts/harvester-networkfs-manager/templates/_helpers.tpl
- charts/harvester-networkfs-manager/templates/crds/harvesterhci.io_networkfilesystems.yaml
- charts/harvester-networkfs-manager/templates/daemonset.yaml
- charts/harvester-networkfs-manager/templates/rbac.yaml
- charts/harvester-networkfs-manager/values.yaml
add new chart `networkfs-manager`
> charts: initinal commit for networkfs-manager

- charts/harvester-networkfs-manager/.helmignore
- charts/harvester-networkfs-manager/Chart.yaml
- charts/harvester-networkfs-manager/templates/NOTES.txt
- charts/harvester-networkfs-manager/templates/_helpers.tpl
- charts/harvester-networkfs-manager/templates/crds/harvesterhci.io_networkfilesystems.yaml
- charts/harvester-networkfs-manager/templates/daemonset.yaml
- charts/harvester-networkfs-manager/templates/rbac.yaml
- charts/harvester-networkfs-manager/values.yaml
> charts: initinal release for harvester-networkfs-manager

- charts/harvester-seeder/Chart.yaml
Related issue: harvester/harvester#6158
> chore: bump harvester-seeder chart to 0.4.0

- charts/harvester-node-disk-manager/templates/crds/harvesterhci.io_blockdevices.yaml
- charts/harvester-node-disk-manager/templates/crds/harvesterhci.io_lvmvolumegroups.yaml
- charts/harvester-node-disk-manager/templates/rbac.yaml
- add longhorn v2/lvm fields
- add lvmvolumegroups CRD
- add lvmvolumegroups permission
> charts: update NDM charts

- charts/harvester-node-disk-manager/Chart.yaml
- charts/harvester-node-disk-manager/templates/crds/harvesterhci.io_blockdevices.yaml
- charts/harvester-node-disk-manager/templates/crds/harvesterhci.io_lvmvolumegroups.yaml
- charts/harvester-node-disk-manager/templates/rbac.yaml
- bump charts
- bump image version
> update NDM charts for release

- charts/nvidia-driver-runtime/Chart.yaml
- charts/nvidia-driver-runtime/templates/daemonset.yaml
Release for nvidia-driver-runtime.
Related to https://github.com/harvester/charts/pull/286
> Nvidia driver runtime v0.4.0

- charts/nvidia-driver-runtime/Chart.yaml
- charts/nvidia-driver-runtime/templates/daemonset.yaml
PR updates nvidia-driver-runtime chart to v0.3.0
The chart includes fixes related to https://github.com/harvester/harvester/issues/6487
> Nvidia driver runtime v0.3.0

- charts/harvester-csi-driver-lvm/Chart.yaml
- charts/harvester-csi-driver-lvm/templates/_helpers.tpl
- charts/harvester-csi-driver-lvm/templates/controller.yaml
- charts/harvester-csi-driver-lvm/templates/csi.yaml
- charts/harvester-csi-driver-lvm/templates/rbac.yaml
- rbac: we need capability to operate volumesnapshot
- controller: add snapshotter
- misc cleanup
> charts: update volumesnapshot related fields

- charts/harvester-node-disk-manager/templates/crds/harvesterhci.io_lvmvolumegroups.yaml
> charts: update lvmvolumegroups fields

- charts/nvidia-driver-runtime/Chart.yaml
- charts/nvidia-driver-runtime/templates/daemonset.yaml
release PR for nvidia-driver-runtime chart v0.4.1
> Nvidia driver runtime v0.4.1

- charts/harvester-csi-driver/templates/daemonset.yaml
- charts/harvester-csi-driver/values.yaml
now we can config host StorageClass with helm
> charts: support host StorageClass config on helm chart

- .github/workflows/ci.yaml
- charts/harvester-csi-driver-lvm/Chart.yaml
- charts/harvester-csi-driver-lvm/templates/common.yaml
- tests/snapshotter_volumesnapshotclass.yaml
> charts: add LVM VolumeSnapshotClass as default

- charts/harvester-node-disk-manager/templates/_helpers.tpl
- charts/harvester-node-disk-manager/templates/daemonset.yaml
- charts/harvester-node-disk-manager/templates/rbac.yaml
- charts/harvester-node-disk-manager/templates/webhook.yaml
- charts/harvester-node-disk-manager/values.yaml
add needed CRD files for webhook
> charts: add webhook to node-disk-manager

- charts/harvester-csi-driver/Chart.yaml
- charts/harvester-csi-driver/values.yaml
> charts: release harvester-csi-driver v0.1.20

- charts/harvester-node-disk-manager/Chart.yaml
- charts/harvester-node-disk-manager/values.yaml
- bump latest image version v0.7.6
> charts: release Harvester Node Disk Manager 0.7.6

- charts/harvester-csi-driver/Chart.yaml
- charts/harvester-csi-driver/values.yaml
> charts: bump harvester-csi-driver v0.1.21

- charts/harvester-csi-driver/Chart.yaml
- We did not rely on the specific kube-version, so I remove the limitation of the kube-verson. To prevent some checking will be affected with this annotation.
> charts: update kube-version

- charts/harvester-csi-driver/Chart.yaml
- we missed it on the kube-version update
> charts: update the harvester csi driver version

- charts/harvester-seeder/Chart.yaml
Update seeder chart to v1.5.0-dev.0 to prepare for 1.5 sprint release
> update seeder chart to v1.5.0-dev.0

- charts/harvester-pcidevices-controller/Chart.yaml
- Chart version: 1.5.0-dev.0
- App version: v1.5.0-dev.0
> chore: bump pcidevice to 1.5.0-dev.0

- charts/harvester-vm-dhcp-controller/crds/network.harvesterhci.io_virtualmachinenetworkconfigs.yaml
This is the chart part for harvester/vm-dhcp-controller#43 to work properly.
Related issue: harvester/harvester#7046
> feat: make network config mutable to support mac addr updates

- charts/harvester-vm-import-controller/Chart.yaml
- charts/harvester-vm-import-controller/templates/rbac.yaml
PR contains the following:
- cherry pick commit from charts PR: https://github.com/harvester/charts/pull/301
- update to chart.yaml to release v1.5.0-dev.0 chart
> release vm-import-controller v1.5.0 dev.0

- charts/harvester-network-controller/Chart.yaml
- charts/harvester-network-controller/values.yaml
link: https://github.com/harvester/harvester/issues/7324
> chore: bump harvester-network-controller to 1.5.0-dev.0

- charts/harvester-vm-dhcp-controller/Chart.yaml
- charts/harvester-vm-dhcp-controller/crds/network.harvesterhci.io_virtualmachinenetworkconfigs.yaml
- charts/harvester-vm-dhcp-controller/templates/rbac.yaml
Related issue:
harvester/harvester#7046
harvester/harvester#6240
> Bump vm dhcp controller 1.5.0 dev.2

- charts/nvidia-driver-runtime/Chart.yaml
Update nvidia-driver-runtime to use new versioning scheme
> updating nvidia-driver-runtime to use new versioning scheme

- charts/harvester-pcidevices-controller/Chart.yaml
- https://github.com/harvester/harvester/issues/7324
- tag: https://github.com/harvester/pcidevices/releases/tag/v1.5.0-dev.1
- addon: https://github.com/harvester/addons/pull/62
> chore: bump pcidevices-v1.5.0-dev.1

- charts/harvester-csi-driver-lvm/templates/uninstall-hook.yaml
- charts/harvester-csi-driver-lvm/values.yaml
related issue: https://github.com/harvester/harvester/issues/7935
> charts: add pre-delete hook to remove the unused validator

- charts/harvester-node-disk-manager/Chart.yaml
- charts/harvester-node-disk-manager/values.yaml
Bump node-disk-manager for v1.4.x release
Bump node-disk-manager for v1.4.x release
> charts: bump node-disk-manager 0.7.8

- charts/harvester-node-manager/Chart.yaml
- charts/harvester-node-manager/values.yaml
Need to bump node-manager to pick up https://github.com/harvester/node-manager/pull/77 for Harvester v1.4.3 release
This PR
https://github.com/harvester/harvester/issues/7712
> chore: bump node-manager to v0.3.4

- charts/harvester-csi-driver-lvm/Chart.yaml
- charts/harvester-csi-driver-lvm/templates/uninstall-hook.yaml
- charts/harvester-csi-driver-lvm/values.yaml
related issue: https://github.com/harvester/harvester/issues/7935
> add lvm pre-delete hook to remove validator

- charts/harvester-cloud-provider/questions.yml
- charts/harvester-cloud-provider/values.yaml
https://github.com/harvester/harvester/issues/8204
> feat(harvester-cloud-provider): change default cloud config path

- .github/workflows/ci.yaml
> ci: improve the stability of chart testing

- charts/harvester-pcidevices-controller/Chart.yaml
- charts/nvidia-driver-runtime/Chart.yaml
PR bumps chart versions for nvidia driver runtime and pcidevices to use version v1.5.1-dev.0
> chart release for pcidevices and nvidia-driver-runtime for v1.5.1-dev.0

- charts/harvester-node-manager/Chart.yaml
> chore: bump node-manager to 1.5.1-dev.1

- charts/kubeovn-operator/.helmignore
- charts/kubeovn-operator/Chart.yaml
- charts/kubeovn-operator/crds/crd.yaml
- charts/kubeovn-operator/templates/_helpers.tpl
- charts/kubeovn-operator/templates/deployment.yaml
- charts/kubeovn-operator/templates/rbac.yaml
- charts/kubeovn-operator/templates/secret.yaml
- charts/kubeovn-operator/templates/service.yaml
- charts/kubeovn-operator/templates/serviceaccount.yaml
- charts/kubeovn-operator/values.yaml
PR introduces the chart for kubeovn-operator.
This is the first step to packaging the same as an addon.
https://github.com/harvester/harvester/issues/7413
> introduce chart for kubeovn operator

- charts/kubeovn-operator/.helmignore
- charts/kubeovn-operator/Chart.yaml
- charts/kubeovn-operator/crds/crd.yaml
- charts/kubeovn-operator/templates/_helpers.tpl
- charts/kubeovn-operator/templates/deployment.yaml
- charts/kubeovn-operator/templates/rbac.yaml
- charts/kubeovn-operator/templates/secret.yaml
- charts/kubeovn-operator/templates/service.yaml
- charts/kubeovn-operator/templates/serviceaccount.yaml
- charts/kubeovn-operator/values.yaml
Release chart for kubovn-operator
This is needed for packaging as a harvester addon.
https://github.com/harvester/harvester/issues/7413
> Release kubeovn-operator v1.13.13-rc1 chart

- .github/workflows/ci.yaml
We have our own version format, so we need the version checking on CI side.
Add version checking.
> CI: add version format checking

- .github/workflows/ci.yaml
- charts/harvester-node-manager/Chart.yaml
The node-manager version is incorrect.
We add the new ci checking for the version format and fix the version of node-manager.
We add the new ci checking for the version format and fix the version of node-manager.
> add ci for version checking and fix node-manager version

- charts/harvester-csi-driver/templates/rbac.yaml
- we need this permission for the new harvester csi driver
we need this permission for the new harvester csi driver (taint the non-graceful node)
add node update permission
> charts: add node update capability

- charts/harvester-csi-driver/Chart.yaml
- charts/harvester-csi-driver/templates/rbac.yaml
- charts/harvester-csi-driver/values.yaml
Bump harvester csi driver 0.1.24
Bump harvester csi driver 0.1.24
> Bump new harvester csi driver

- charts/kubeovn-operator-crd/Chart.yaml
- charts/kubeovn-operator/Chart.yaml
- charts/kubeovn-operator/templates/secret.yaml
Release kubeovn-operator chart v1.13.13-rc4
https://github.com/harvester/harvester/issues/8676
> Kubeovn operator 1.13.13 rc4

- charts/kubeovn-operator-crd/Chart.yaml
PR updates kubeovn-operator-crd chart to bring it line with version of kubeovn-operator chart.
https://github.com/harvester/harvester/issues/8820
> update kubeovn-operator-crd release

- charts/harvester-vm-dhcp-controller/Chart.yaml
> chore: bump vm-dhcp-controller to 1.6.0

- charts/harvester-load-balancer/Chart.yaml
- charts/harvester-network-controller/Chart.yaml
- charts/harvester-networkfs-manager/Chart.yaml
- charts/harvester-node-disk-manager/Chart.yaml
- charts/harvester-node-manager/Chart.yaml
- charts/harvester-pcidevices-controller/Chart.yaml
- charts/harvester-seeder/Chart.yaml
- charts/harvester-vm-import-controller/Chart.yaml
- charts/nvidia-driver-runtime/Chart.yaml
Bump various components for v1.7.0-dev
Bump various components for v1.7.0-dev
> charts: various bump for the v1.7.0-dev
