harvester/charts

- charts/harvester-network-controller/.helmignore
- charts/harvester-network-controller/Chart.yaml
- charts/harvester-network-controller/README.md
- charts/harvester-network-controller/crds/network.harvesterhci.io_clusternetworks.yaml
- charts/harvester-network-controller/crds/network.harvesterhci.io_nodenetworks.yaml
- charts/harvester-network-controller/templates/NOTES.txt
- charts/harvester-network-controller/templates/_helpers.tpl
- charts/harvester-network-controller/templates/daemonset.yaml
- charts/harvester-network-controller/templates/deployment.yaml
- charts/harvester-network-controller/templates/rbac.yaml
- charts/harvester-network-controller/values.yaml
- Migrate harvester network controller chart from [harvester/dependency_charts/harvester-network-controller](https://github.com/harvester/harvester/tree/master/deploy/charts/harvester/dependency_charts/harvester-network-controller) to harvester/charts
- update the CRD to mapping with the master-head version of https://github.com/harvester/network-controller-harvester
> Add harvester network controller chart

- charts/harvester-csi-driver/templates/deployment.yaml
- charts/harvester-csi-driver/values.yaml
Update images to newer versions that Longhorn v1.2.0 is using.
> update CSI component images in harvester-csi-driver chart

- charts/harvester-node-disk-manager/.helmignore
- charts/harvester-node-disk-manager/Chart.yaml
- charts/harvester-node-disk-manager/crds/harvesterhci.io_blockdevices.yaml
- charts/harvester-node-disk-manager/templates/NOTES.txt
- charts/harvester-node-disk-manager/templates/_helpers.tpl
- charts/harvester-node-disk-manager/templates/daemonset.yaml
- charts/harvester-node-disk-manager/templates/rbac.yaml
- charts/harvester-node-disk-manager/values.yaml
This is the very first version of helm chart for harvester/node-disk-manager. The node-disk manager ~~is still under construction and the API group might change to harvesterhci.io in the near future~~. But IMO the chart itself is worth a check now (to make sure I didn't go too far away.)
Edited:
- There is already an image on docker hub:https://hub.docker.com/r/rancher/harvester-node-disk-manager
- The API group migrations is done (harvester/node-disk-manager#1)
> Add harvester node disk manager chart

- charts/harvester-network-controller/templates/deployment.yaml
https://github.com/harvester/charts/runs/4405789084?check_suite_focus=true
Fix the error found by CI
```
Error: unable to build kubernetes objects from release manifest: error
validating "": error validating data:
ValidationError(Deployment.spec.template.spec.containers[0].args[1]):
invalid type for io.k8s.api.core.v1.Container.args: got "map", expected
"string" 968
```
> Fix helper image arg CI error

- charts/harvester-cloud-provider/questions.yml
- charts/harvester-cloud-provider/templates/deployment.yaml
- charts/harvester-cloud-provider/values.yaml
- https://github.com/harvester/harvester/issues/2031
According to UI code, `clusterName` will auto-set to the request body.  Other auto-set fields can refer to these [code](https://github.com/rancher/dashboard/blob/cbdcf7107e10d8e725ec9bdd510084c9ae545877/pages/c/_cluster/apps/charts/install.vue#L807-L813) 。
Change `Values.clusterName` to `Values.global.cattle.clusterName`
> Remove CPI cluster name question

- charts/harvester-pcidevices-controller/Chart.yaml
- charts/harvester-pcidevices-controller/templates/daemonset.yaml
- charts/harvester-pcidevices-controller/templates/service.yaml
- charts/harvester-pcidevices-controller/templates/serviceaccount.yaml
Change splits daemonset.yaml and puts service definition in a separate file for better readability,.
> pcidevices: fix for service yaml

- charts/harvester-pcidevices-controller/values.yaml
We hit OOM with the previous value and observe the average MEM use for 4-node clusters is between 150 to 200.
The CPU limit is also increased a little bit and we can fine-tune later.
Signed-off-by: Kiefer Chang <kiefer.chang@suse.com>
> pci-device-controller: increase resource limit

- charts/harvester-vm-import-controller/templates/deployment.yaml
- charts/harvester-vm-import-controller/templates/pvc.yaml
- charts/harvester-vm-import-controller/values.yaml
**Description:**
disable `vm-importer` PVC by default so it won't run over the Harvester minimum storage request.
> fix: disable importer pvc by default

- charts/harvester-vm-import-controller/Chart.yaml
- charts/harvester-vm-import-controller/templates/service.yaml
Fixes for vm-import-controller to have a fixed service name.
Related to issue with testing of: https://github.com/harvester/harvester/issues/2274
> fixes for vm-import-controller

- charts/harvester-pcidevices-controller/templates/serviceaccount.yaml
PR introduces changes for rbac update to pcidevices helm chart to allow webhook to access VirtualMachines in kubevirt.io api group.
> rbac update for pcidevices chart

- charts/harvester-pcidevices-controller/templates/daemonset.yaml
The [change to pcidevices](https://github.com/harvester/pcidevices/commit/4bf9e47f08b34729ef075f04e35fc7e204b5fd95) that filters out the management interface was merged, but it depends on a change to the daemonset that gives the pod permission to access the host network and the host PID information. 
I tested this by running `kubectl edit daemonsets.apps -n harvester-system harvester-pcidevices-controller`
And editing these in: 
```yaml
spec:
revisionHistoryLimit: 10
selector:
matchLabels:
app.kubernetes.io/instance: pcidevices-controller
app.kubernetes.io/name: harvester-pcidevices-controller
template:
metadata:
creationTimestamp: null
labels:
app.kubernetes.io/instance: pcidevices-controller
app.kubernetes.io/name: harvester-pcidevices-controller
spec:
hostNetwork: true
hostPID: true …
```
> Fix permissions for the mgmt interface filtering

- charts/harvester-pcidevices-controller/templates/serviceaccount.yaml
additional permissions for harvester-pcidevices-controller cluster role to allow it to watch vlanconfigs
> pcidevices controller helm rbac update

- charts/harvester-pcidevices-controller/templates/serviceaccount.yaml
Minor change to allow pcidevices controller service account to be able to create/update leases.coordination objects.
> updates for pcidevices controller

- charts/harvester-pcidevices-controller/templates/daemonset.yaml
PR introduces a minor change to the pcidevices controller chart to do the following:
* drop hostNetwork
* mount /proc into /host/proc
Related to: https://github.com/harvester/pcidevices/pull/52
> drop hostNetwork for pcidevices

- charts/harvester-network-controller/values.yaml
Before:
$ helm package .
Successfully packaged chart and saved it to: /.../charts/charts/harvester-network-controller/harvester-network-controller-0.3.2.tgz
$ helm upgrade --dry-run -n harvester-system harvester harvester-network-controller-0.3.2.tgz | grep beta\.kubernetes\.io\/os | wc -l
1
After:
$ helm package .
Successfully packaged chart and saved it to: /.../charts/charts/harvester-network-controller/harvester-network-controller-0.3.2.tgz
$ helm upgrade --dry-run -n harvester-system harvester harvester-network-controller-0.3.2.tgz | grep beta\.kubernetes\.io\/os | wc -l
0
Related-to: https://github.com/harvester/harvester/issues/2899
> Remove use of deprecated label

- charts/harvester-network-controller/Chart.yaml
- charts/harvester-network-controller/values.yaml
Related issue: https://github.com/harvester/harvester/issues/2899
Signed-off-by: Connor Kuehl <connor.kuehl@suse.com>
> Release deprecated label fix

- charts/harvester-cloud-provider/values.yaml
Use the kube-vip mirrored image instead of the official image because of the requirement from RKE2.
Related issue: https://github.com/rancher/rke2/issues/4184
> Use the kube-vip mirrored image instead

- charts/vcluster/.helmignore
- charts/vcluster/Chart.yaml
- charts/vcluster/README.md
- charts/vcluster/templates/NOTES.txt
- charts/vcluster/templates/_helpers.tpl
- charts/vcluster/templates/_k3s_helpers.tpl
- charts/vcluster/templates/coredns.yaml
- charts/vcluster/templates/daemonset-hostpath-mapper.yaml
- charts/vcluster/templates/ingress.yaml
- charts/vcluster/templates/init-configmap.yaml
- charts/vcluster/templates/limitrange.yaml
- charts/vcluster/templates/networkpolicy.yaml
- charts/vcluster/templates/pdb.yaml
- charts/vcluster/templates/pre-install-hook-secret.yaml
- charts/vcluster/templates/rbac/clusterrole.yaml
- charts/vcluster/templates/rbac/clusterrolebinding.yaml
- charts/vcluster/templates/rbac/role.yaml
- charts/vcluster/templates/rbac/rolebinding.yaml
- charts/vcluster/templates/resourcequota.yaml
- charts/vcluster/templates/service.yaml
- charts/vcluster/templates/serviceaccount.yaml
- charts/vcluster/templates/statefulset-service.yaml
- charts/vcluster/templates/statefulset.yaml
- charts/vcluster/templates/workloadserviceaccount.yaml
- charts/vcluster/values.yaml
The upstream vcluster helm chart does not contain `appVersion` defined in the `Chart.yaml`
This results in the version check in the helm controller uninstall to fail. As a result of this when rancher-vcluster addon is disabled the chart is not uninstalled.
> introduction of patched vcluster chart

- charts/vcluster/.helmignore
- charts/vcluster/Chart.yaml
- charts/vcluster/README.md
- charts/vcluster/templates/NOTES.txt
- charts/vcluster/templates/_helpers.tpl
- charts/vcluster/templates/_k3s_helpers.tpl
- charts/vcluster/templates/coredns.yaml
- charts/vcluster/templates/daemonset-hostpath-mapper.yaml
- charts/vcluster/templates/ingress.yaml
- charts/vcluster/templates/init-configmap.yaml
- charts/vcluster/templates/limitrange.yaml
- charts/vcluster/templates/networkpolicy.yaml
- charts/vcluster/templates/pdb.yaml
- charts/vcluster/templates/pre-install-hook-secret.yaml
- charts/vcluster/templates/rbac/clusterrole.yaml
- charts/vcluster/templates/rbac/clusterrolebinding.yaml
- charts/vcluster/templates/rbac/role.yaml
- charts/vcluster/templates/rbac/rolebinding.yaml
- charts/vcluster/templates/resourcequota.yaml
- charts/vcluster/templates/service.yaml
- charts/vcluster/templates/serviceaccount.yaml
- charts/vcluster/templates/statefulset-service.yaml
- charts/vcluster/templates/statefulset.yaml
- charts/vcluster/templates/workloadserviceaccount.yaml
- charts/vcluster/values.yaml
PR for vcluster chart release v0.15.2
Needed for vcluster addon: https://github.com/harvester/experimental-addons/pull/1
> vcluster release v0.15.2

- charts/harvester-load-balancer/Chart.yaml
- charts/harvester-load-balancer/values.yaml
Add loadbalancer v0.2.0 official release tag and address os-dep CVE issues.
Notes: this is an identical tag to the previous `v0.2.0-rc4` tag https://github.com/harvester/load-balancer-harvester/tags
> Add loadbalancer v0.2.0 release

- .github/workflows/ci.yaml
- charts/harvester-seeder/Chart.yaml
- charts/harvester-seeder/templates/deployment.yaml
- charts/harvester-seeder/templates/rbac.yaml
- charts/harvester-seeder/templates/service.yaml
PR introduces changes for harvester-seeder to support newly introduced webhook for validating inventory objects.
harvester-seeder PR dependent on this: https://github.com/harvester/seeder/pull/17
> updates for harvester-seeder to support webhook

- charts/harvester-node-manager/Chart.yaml
- charts/harvester-node-manager/values.yaml
To make the node-manager run on the `etcd` node, we need to update tolerations.
> Update node-manager version and tolerations

- charts/harvester-csi-driver/Chart.yaml
- appVersion to v0.1.6
v0.1.6 contains a new checking mechanism if
the guest VM has a different naming style.
> chart: bump harvester-csi-driver v0.1.17

- charts/harvester-cloud-provider/values.yaml
After setting up guest cluster with this configuration (control-plane + ETCD separate from worker in different pool)  mentioned in Test Plan. 
When you create load balancer type service with harvester cloud provider annotation, the load balancer type service `EXTERNAL_IP` is stuck in pending status 
After discussion in https://github.com/harvester/harvester/issues/4678, the reason is `kube-vip` toleration doesn't matched any node taint.
Add one more toleration in `kube-vip` DaemonSet. It should works in all cases listed in Test Plan.
Bump PR is https://github.com/harvester/charts/pull/203
https://github.com/harvester/harvester/issues/4678
1. We choose harvester cloud provider. 
2. Set up cloud-config in each node for later usage because we need to reinstall harvester-cloud-provider …
> fix: add kube-vip toleration to match node taint in harvester-cloud-provider

- charts/harvester-cloud-provider/Chart.yaml
- charts/harvester-cloud-provider/values.yaml
according to updating https://github.com/harvester/charts/pull/202, bump harvester-cloud-provider version.
> charts: bump harvester-cloud-provider 0.2.3

- charts/harvester-node-manager/templates/rbac.yaml
A new controller in harvester-node-manager emits events whenever it modifies one of the files under its management. In order to do so successfully, it needs the capability added to the node-manager chart RBAC.
> harvester-node-manager: update RBAC for eventing

- charts/harvester-node-manager/Chart.yaml
- charts/harvester-node-manager/templates/_helpers.tpl
- charts/harvester-node-manager/templates/crds/node.harvesterhci.io_cloudinits.yaml
- charts/harvester-node-manager/templates/deployment.yaml
- charts/harvester-node-manager/templates/rbac.yaml
- charts/harvester-node-manager/templates/service.yaml
- charts/harvester-node-manager/values.yaml
- Chart template updated.
- https://github.com/harvester/charts/pull/205
- https://github.com/harvester/charts/pull/206
- And a new image tag: https://github.com/harvester/node-manager/releases/tag/v0.2.0
> Bump node-manager chart and appVersion to v0.2.0

- charts/harvester-node-manager/Chart.yaml
- charts/harvester-node-manager/templates/deployment.yaml
Related issue: https://github.com/harvester/harvester/issues/5119
Changes:
0e0dadd Require CloudInit .spec.contents to be valid YAML
> Bump node manager

- charts/harvester-node-manager/templates/deployment.yaml
**Problem:**
If the Helm chart is installed with more replicas than there are nodes, there will be redundant harvester-node-manager-webhook pods running on a single node.
**Solution:**
Use the `management.cattle.io/scale-available` annotation to grow/reduce the number of replicas when nodes are added/removed.
**Related Issue:** https://github.com/harvester/harvester/issues/5149
**Test plan:**
1. Start with a single node cluster, install the Helm chart with `--set webhook.replicas=3` (this is the default value)
2. Assert there is only 1 replica (`kubectl get pods -n harvester-system | grep harvester-node-manager-webhook | grep Running | wc -l`)
3. Add an agent node
4. Assert that there are 2 replicas (`kubectl get pods -n harvester-system | grep harvester-node-manager-webhook | grep …
> Use scale-available annotation for node-manager webhook

- charts/harvester-vm-dhcp-controller/crds/network.harvesterhci.io_ippools.yaml
- charts/harvester-vm-dhcp-controller/crds/network.harvesterhci.io_virtualmachinenetworkconfigs.yaml
Add declarative validations and some additional fields to support agent upgrades
Ref:
- harvester/vm-dhcp-controller#18
- harvester/vm-dhcp-controller#23
> feat(crd): update vm-dhcp-controller crd manifests

- charts/harvester-node-manager/templates/deployment.yaml
**Problem:**
If the Helm chart specifies BOTH the `management.cattle.io/scale-available` annotation and .spec.replicas, then the mcc-harvester bundle will be considered Not Ready in clusters where the number of nodes is fewer than .spec.replicas because the management.cattle.io/scale-available scales the replica up/down based on node availability up to the desired count.
This will prevent upgrading the Harvester cluster on a 1 or 2 node cluster when the number of replicas is set to 3.
**Solution:**
Defer completely to the management.cattle.io/scale-available annotation instead of specifying .spec.replicas.
**Related Issue:** https://github.com/harvester/harvester/issues/5212
**Test plan:**
Assert that the .spec.replicas field is not generated in the Helm chart when …
> node-manager-webhook: Defer replica scaling to scale-available annotation

- charts/harvester-node-manager/templates/deployment.yaml
**Problem:**
The harvester-node-manager-webhook is not scheduled on witness nodes, so when the deployment is auto-scaled, it can result in redundant pods on one node.
```console
harv1:~ # kubectl get nodes
NAME    STATUS   ROLES                       AGE   VERSION
etcd1   Ready    <none>                      47m   v1.27.10+rke2r1
harv1   Ready    control-plane,etcd,master   18h   v1.27.10+rke2r1
harv1:~ # kubectl get pods -n harvester-system -o=custom-columns='NAME:.metadata.name,NODE:spec.nodeName' | grep node-manager-webhook
harvester-node-manager-webhook-6b8cfcbc7b-lnhhc         harv1
harvester-node-manager-webhook-6b8cfcbc7b-pk5wl         harv1
```
**Solution:**
Since the node-manager daemonset requires the node-manager-webhook to function properly, use the node-manager's tolerations …
> node-manager-webhook: Use node-manager tolerations

- charts/harvester-cloud-provider/values.yaml
Since RKE1 and RKE2 have slightly different node label keys:
- RKE1: `node-role.kubernetes.io/controlplane`
- RKE2: `node-role.kubernetes.io/control-plane`
We need to be compatible with both two types of guest cluster deployment, hence moving the nodeSelector to nodeAffinity.
Related issue: harvester/harvester#5247
> fix: add nodeaffinity for kube-vip daemonset

- charts/harvester-vm-dhcp-controller/templates/rbac.yaml
The validating admission webhook of vm-dhcp-controller needs to compare the user input cidr with the cluster-wide service cidr. Such information is retrieved from the node objects. So the webhook must have the LIST permission on nodes objects.
Related issue: harvester/harvester#5153
Depends on harvester/vm-dhcp-controller#27
> fix: grant node list permission to vm-dhcp-webhook

- charts/harvester-cloud-provider/templates/deployment.yaml
Changing the value to 1 from the default 25% remedies the deployment update stuck problem in single-node clusters due to pod antiaffinity.
Related issue: harvester/harvester#5348
> fix: add maxUnavailable for cloud provider upgrade

- charts/harvester-csi-driver/Chart.yaml
- charts/harvester-csi-driver/values.yaml
- release images for both x86/aarch64 platform
> charts: bump harvester-csi-driver v0.1.18

- .github/workflows/ci.yaml
- charts/harvester-pcidevices-roles/Chart.yaml
- charts/harvester-pcidevices-roles/templates/harvester-pcidevices-admin.yaml
- charts/harvester-pcidevices-roles/templates/harvester-pcidevices-readonly.yaml
- tests/roletemplate_crd.yaml
The chart introduces the ability to define custom pcidevices roles for the rancher cluster.
This chart will be released into rancher/charts for installation on the rancher cluster.
> initial commit for harvester pcidevices roles charts

- charts/harvester-vm-import-controller/templates/rbac.yaml
PR https://github.com/harvester/vm-import-controller/pull/31 allows end users to specify a custom storage class during the import process. 
To allow lookup of storage class the vm-import-controller now needs access to get and list storageclass objects in the cluster.
The PR adds the additional permissions needed for the same.
> update rbac requirements for vm-import-controller

- charts/harvester-vm-import-controller/Chart.yaml
- charts/harvester-vm-import-controller/templates/rbac.yaml
PR cherry picks commits from https://github.com/harvester/charts/pull/254
and updates vm-import-controller to release v0.4.0
> Release vm import v0.4.0

- charts/harvester-node-disk-manager/Chart.yaml
Bump NDM again as action failed and no 0.7.1 publish in gh-page, https://github.com/harvester/charts/actions/runs/10503401996, hope this time it will pass...
```
Looking up latest tag...
Discovering changed charts since 'harvester-load-balancer-0.4.0'...
Installing chart-releaser...
Adding cr directory to PATH...
Packaging chart 'charts/harvester-node-manager'...
Successfully packaged chart in /home/runner/work/charts/charts/charts/harvester-node-manager and saved it to: .cr-release-packages/harvester-node-manager-0.3.0.tgz
Releasing charts...
Error: error creating GitHub release harvester-node-manager-0.3.0: POST https://api.github.com/repos/harvester/charts/releases: 422 Validation Failed [{Resource:Release Field:tag_name Code:already_exists Message:}]
```
The root cause was I changed …
> Bump node-disk-manager to 0.7.2

- charts/nvidia-driver-runtime/templates/daemonset.yaml
Related to: https://github.com/harvester/harvester/issues/6487
Looks like there has been a change in nvidia driver packaging which needs firmware files to be exposed to the underlying host.
https://github.com/NVIDIA/gpu-operator/commit/c4dce746b18dae1850cb2e6eadded6d28a76013d
The PR attempts to address the same.
> include additional mounts to stage driver firmware

- charts/harvester-node-disk-manager/Chart.yaml
- charts/harvester-node-disk-manager/templates/crds/harvesterhci.io_lvmvolumegroups.yaml
- charts/harvester-node-disk-manager/values.yaml
- s/desireState/desiredState
- bump image version v0.7.3
> charts: update lvmvolumegroups fields and version bump

- charts/harvester-csi-driver-lvm/templates/_helpers.tpl
- charts/harvester-csi-driver-lvm/templates/controller.yaml
- charts/harvester-csi-driver-lvm/templates/csi.yaml
- charts/harvester-csi-driver-lvm/templates/rbac.yaml
- charts/harvester-csi-driver-lvm/templates/webhook.yaml
- charts/harvester-csi-driver-lvm/values.yaml
update webhook related charts
I will create a corresponding release PR once the lvm csi driver PR (https://github.com/harvester/csi-driver-lvm/pull/6) is merged
> charts: update lvm csi driver webhook related charts

- charts/nvidia-driver-runtime/templates/daemonset.yaml
PR rolls back the original change in the nvidia driver-runtime chart to add additional firmware search paths.
PR also now mounts /lib/firmware directly into the daemonset as v1.4.x makes /lib/firmware an overlay fs.
Related to: https://github.com/harvester/harvester/issues/6487
> rollback changes from pr-286 and mount /lib/firmware into daemonset

- .github/workflows/ci.yaml
- charts/harvester-csi-driver-lvm/templates/common.yaml
- tests/snapshotter_volumesnapshotclass.yaml
We need LVM `VolumeSnapshotClass` because our LVM csi driver supports volume snapshot
> charts: add LVM VolumeSnapshotClass as default

- charts/harvester-vm-dhcp-controller/Chart.yaml
Bump harvester-vm-dhcp-controller
- chart version: 0.3.2
- app version: v0.3.2
> chore: bump vm-dhcp-controller to 0.3.2

- charts/harvester-vm-dhcp-controller/Chart.yaml
- chart version: 0.3.3
- app version: v0.3.3
Related issue: harvester/harvester#6942
> chore: bump vm-dhcp-controller to 0.3.3

- charts/harvester-cloud-provider/Chart.yaml
We did not rely on the specific kube-version, so I remove the limitation of the kube-verson. To prevent some checking will be affected with this annotation. Also, update chart version to 0.2.8.
> harvester-cloud-provider: update kube-version and chart version

- .github/workflows/ci.yaml
This PR removes the unneeded python3 dependency from GHA. As of yesterday, [CI started failing](https://github.com/harvester/charts/actions/runs/12738947411/job/35503198243#step:5:6) due to missing python 3.7 library. The `ubuntu:latest` has been bumped to [ubuntu 24.04.5](https://github.com/harvester/charts/actions/runs/12738947411/job/35503198243#step:1:4). It was still at [ubuntu 22.04.5](https://github.com/harvester/charts/actions/runs/12684586127/job/35353514223#step:1:4) about 4 days ago.
Both the `lint-test` and `release` jobs passed in my [`release` fork](https://github.com/ihcsim/harvester-charts/actions/runs/12753416927/job/35545049441), without requiring python 3.
> chore: remove unneeded python3 dependency from GHA

- charts/harvester-csi-driver/templates/deployment.yaml
This PR updates the CSI controller chart with new node affinity and pod anti-affinity rules to ensure that, within the guest cluster:
* The controller replicas _should_ be scheduled to run only on _distinct_ control plane nodes
* The controller replicas _must_ be scheduled to run on control plane nodes, not on worker nor etcd nodes
The first rule is a soft constraint. If there are more replicas than control plane nodes, the K8s scheduler can run multiple replicas on the same nodes. The second rule is a hard constraint i.e. the controller must only run on control plane nodes and never on worker nodes.
Note that I am not sure if we want to make these rules user-configurable.
Relevant issue: https://github.com/harvester/harvester/issues/7189
Create a RKE2 guest cluster with 2 control plane …
> feat: add csi controller affinity rules

- charts/harvester-vm-dhcp-controller/Chart.yaml
- Chart version: 1.5.0-dev.1
- App version: v1.5.0-dev.1
> chore: bump vm-dhcp-controller to 1.5.0-dev.1

- charts/harvester-csi-driver/Chart.yaml
- charts/harvester-csi-driver/templates/deployment.yaml
- charts/harvester-csi-driver/values.yaml
This PR cherry-picked #323 from the `master` branch.
Relevant issue: https://github.com/harvester/harvester/issues/7189
Note #326 needs to be merged for CI to pass.
> feat: add CSI controller affinity/anti-affinity rules

- charts/harvester-vm-dhcp-controller/templates/rbac.yaml
Decoupling IPPools and NADs means the relationship between the two parties will be built upon labels. The controller needs to update the referenced NADs with appropriate labels, hence the UPDATE permission should be granted to the controller's service account.
Related issue: harvester/harvester#6240
> fix: grant nad update permission to vm-dhcp-controller

- charts/harvester-node-disk-manager/Chart.yaml
- charts/harvester-node-disk-manager/values.yaml
```
bump node-disk-manager v1.5.0-dev.2
```
Release here: https://github.com/harvester/node-disk-manager/releases/tag/v1.5.0-dev.2
> charts: bump node-disk-manager v1.5.0-dev.2

- charts/harvester-csi-driver-lvm/templates/uninstall-hook.yaml
- we should use the lvm webhook service account
> charts: correct the serviceAccountName to remove validator

- charts/nvidia-driver-runtime/Chart.yaml
- charts/nvidia-driver-runtime/values.yaml
This PR changed the nvidia-driver-runtime's image pull policy setting to `IfNotPresent` to reduce deployment friction in air-gapped environment.
Issue: https://github.com/harvester/harvester/issues/8000
> chore: change nvidia driver image pull policy to IfNotPresent

- charts/harvester-vm-dhcp-controller/Chart.yaml
- Chart version: 1.5.0
- App version: v1.5.0
> chore: bump vm-dhcp-controller to 1.5.0

- charts/nvidia-driver-runtime/values.yaml
This PR backports #353 to `master`. The versions in `charts/nvidia-driver-runtime/Chart.yaml` weren't bumped in previous commits. Let me know if they need to be.
> chore: change nvidia-driver-toolset pull policy to IfNotPresent (#353)

- charts/harvester-csi-driver-lvm/templates/uninstall-hook.yaml
- charts/harvester-csi-driver-lvm/values.yaml
The old kubectl image is too old.
Also, we would like to define the image pullPolicy with a dynamic definition.
- bump kubectl image v1.32.3
- add pullPolicy for uninstall-hook
> charts: add pullPolicy and bump kubectl image

- charts/harvester-node-disk-manager/Chart.yaml
- For the latest image version v0.7.11
We need the latest NDM image to resolve the duplicated device path issue. 
Bump chart 0.7.9 with the latest image v0.7.11
> charts: bump node-disk-manager 0.7.9

- charts/harvester-load-balancer/Chart.yaml
- charts/harvester-network-controller/Chart.yaml
- charts/harvester-networkfs-manager/Chart.yaml
- charts/harvester-node-disk-manager/Chart.yaml
- charts/harvester-node-disk-manager/values.yaml
- charts/harvester-node-manager/Chart.yaml
- charts/harvester-seeder/Chart.yaml
- charts/harvester-vm-import-controller/Chart.yaml
Bump all the default shipped charts and app versions for preparing the v1.5.1-rc1 release. pcidevices and nvidia-driver-runtime charts were handled in #367. This PR takes care the rest.
Note: All the charts were on 1.5.0, and we need first to bump them to 1.5.0-dev.0 so that we can leverage the CI task to automate the RC1 bump. This is typically done by each component owner, as they are the ones who work on the features and fixes, and know when it's ready to release a new version of the component.
> chore: bump charts jumping to 1.5.1 with dev versions

- charts/kubeovn-operator/templates/deployment.yaml
Currently kubeovn-operator chart uses `version` for kubeovn images based on value of `Chart.Appversion`
This causes issues as rc* tags are not valid kubovn image tags.
PR drops the version argument, which results in operator defaulting to the default version in operator package.
https://github.com/harvester/kubeovn-operator/pull/7
https://github.com/harvester/harvester/issues/7413
> minor change to kubeovn operator to drop version argument

- charts/harvester-vm-dhcp-controller/Chart.yaml
chore: bump vm-dhcp-controller to 1.5.1
- Chart version: 1.5.1
- App version: v1.5.1
> bump vm dhcp controller 1.5.1

- charts/kubeovn-operator/templates/secret.yaml
PR https://github.com/harvester/kubeovn-operator/pull/9 adds kubeovn webhook to be managed by the kubeovn-operator
For the webhook to work, a change is needed to the webhook certs to include the SAN for kubeovn-webhook as well the CA cert.
This can then be used by the operator to manage the lifecycle of the kubeovn-webhook.
https://github.com/harvester/harvester/issues/8676
> support for kubeovn-webhook

- charts/kubeovn-operator/values.yaml
Change kubeovn default pod and service cidr ranges to avoid overlap with calico cidr range.
this is essential to ensure that pod to pod traffic does not break on calico
https://github.com/harvester/harvester/issues/8820
> change kubeovn-operator default cidr ranges
